<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Domain\ConvivenciaPix.Domain.csproj" />
    <ProjectReference Include="..\Application\ConvivenciaPix.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="Quartz" />
    <PackageReference Include="Quartz.Extensions.Hosting" />
    <PackageReference Include="Quartz.Extensions.DependencyInjection" />
    <PackageReference Include="System.Security.Cryptography.Xml" />
  </ItemGroup>

</Project>
