// <auto-generated />
using System;
using ConvivenciaPix.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConvivenciaPix.Infrastructure.Migrations
{
    [DbContext(typeof(CoexistenceDbContext))]
    [Migration("20260430195908_AddDiscrepancyTable")]
    partial class AddDiscrepancyTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConvivenciaPix.Domain.Entities.SpiDiscrepancy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationSource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("IdSystemA")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("IdSystemB")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SystemAValue")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("SystemBValue")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("IdSystemA", "DetectedAt")
                        .HasDatabaseName("IX_SpiDiscrepancies_IdSystemA_DetectedAt");

                    b.ToTable("SpiDiscrepancies", (string)null);
                });

            modelBuilder.Entity("ConvivenciaPix.Domain.Entities.SpiPendingSystemBMsg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("IdSystemB")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("PayeeId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("PayerId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("RawXmlBase64")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("DATETIMEOFFSET");

                    b.HasKey("Id");

                    b.HasIndex("IdSystemB")
                        .IsUnique()
                        .HasDatabaseName("IX_SpiPendingSystemBMsg_IdSystemB");

                    b.HasIndex("Timestamp", "Amount")
                        .HasDatabaseName("IX_SpiPendingSystemBMsg_Timestamp_Amount");

                    b.ToTable("SpiPendingSystemBMsg", (string)null);
                });

            modelBuilder.Entity("ConvivenciaPix.Domain.Entities.SpiSentMsg", b =>
                {
                    b.Property<string>("IdSystemA")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("IdSystemB")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("CorrelationSource")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2");

                    b.HasKey("IdSystemA", "IdSystemB");

                    b.HasIndex("IdSystemA")
                        .IsUnique()
                        .HasDatabaseName("IX_SpiSentMsg_IdSystemA");

                    b.HasIndex("IdSystemB")
                        .IsUnique()
                        .HasDatabaseName("IX_SpiSentMsg_IdSystemB");

                    b.ToTable("SpiSentMsg", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
