<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Infrastructure\ConvivenciaPix.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Application\ConvivenciaPix.Application.csproj" />
    <ProjectReference Include="..\..\src\Domain\ConvivenciaPix.Domain.csproj" />
    <ProjectReference Include="..\..\src\SpiProxyApi\ConvivenciaPix.SpiProxyApi.csproj" />
    <ProjectReference Include="..\..\src\SpiCorrelateWorker\ConvivenciaPix.SpiCorrelateWorker.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="Testcontainers.Kafka" />
    <PackageReference Include="Testcontainers.Redis" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>

</Project>
