<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <UserSecretsId>dotnet-ConvivenciaPix.SpiProxyWorker-23273ec1-7098-4b7b-bebb-0c0030748b6d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\ConvivenciaPix.Application.csproj" />
    <ProjectReference Include="..\Infrastructure\ConvivenciaPix.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

</Project>
